<script>
    import Chip from './Chip.svelte';
</script>

<div class="container">
    <!-- <div class="info">
        <Chip text="i" small={true} />
    </div> -->
    <img 
        src="/assets/esp.jpg" 
        alt="Portrait of Esp. Generated by scenario.com, Post-processing by DALL-E."
    />
</div>

<style>
    .container {
        position: relative;
        display: inline-block;
    }

    img {
        width: 300px;
        height: 300px;
        border-radius: 15%;
        object-fit: cover;
    }

    @media only screen and (max-width: 600px) {
        img {
            width: 150px;
            height: 150px;
        }
    }
</style>
